[package]
name = "accordion_task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
color-eyre = "0.6.2"
crossterm = "0.27.0"
csv = "1.3.0"
ratatui = "0.29.0"
