[package]
name = "accordion_core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
color-eyre = "0.6.2"
csv = "1.3.1"
reactive_stores = {version = "0.2.3", optional = true}
serde = { version = "1.0.219", optional = true, features = ["derive"] }
# TODO wasm probably cant depend on csv's for routine defs?

[features]
web = ["dep:reactive_stores", "dep:serde", "chrono/serde"]
